window:
  padding:
    x: 0
    y: 0
  dimensions:
    columns: 90
    lines: 60
  decorations: full

env:
  TERM: xterm-256color

# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: JetBrainsMono Nerd Font Mono
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font Mono
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font Mono
    style: Italic
  bold_italic:
    family: JetBrainsMono Nerd Font Mono
    style: Bold Italic
  size: 18.0
  offset:
    x: 0
    y: 4
  # OS X only: use thin stroke font rendering. Thin strokes are suitable
  # for retina displays, but for non-retina you probably want this set to
  # false.
  use_thin_strokes: true

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: true
dynamic_title: true

# Default colors
primary:
  background: '0x1d2021' # hard contrast
  # background: '0x282828' # normal contrast
  foreground: '0xebdbb2'

# Normal colors
normal:
  black:   '0x282828'
  red:     '0xcc241d'
  green:   '0x98971a'
  yellow:  '0xd79921'
  blue:    '0x458588'
  magenta: '0xb16286'
  cyan:    '0x689d6a'
  white:   '0xa89984'

# Bright colors
bright:
  black:   '0x928374'
  red:     '0xfb4934'
  green:   '0xb8bb26'
  yellow:  '0xfabd2f'
  blue:    '0x83a598'
  magenta: '0xd3869b'
  cyan:    '0x8ec07c'
  white:   '0xebdbb2'

cursor:
  # Cursor style
  #
  # Values for 'style':
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Block

key_bindings:
  - { key: F11, action: ToggleFullscreen }
