window:
  padding:
    x: 0
    y: 0
  dimensions:
    columns: 90
    lines: 60

env:
  TERM: xterm-256color

# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: FiraCode Nerd Font Mono
    style: Retina
  bold:
    family: FiraCode Nerd Font Mono
  italic:
    family: FiraCode Nerd Font Mono
  bold_italic:
    family: FiraCode Nerd Font Mono
  size: 12.0
  offset:
    x: 0
    y: 0

# Colors (Wombat)
colors:
  # Default colors
  primary:
    background: '#1f1f1f'
    foreground: '#e5e1d8'

  # Normal colors
  normal:
    black:   '#000000'
    red:     '#f7786d'
    green:   '#bde97c'
    yellow:  '#efdfac'
    blue:    '#6ebaf8'
    magenta: '#ef88ff'
    cyan:    '#90fdf8'
    white:   '#e5e1d8'

  # Bright colors
  bright:
    black:   '#b4b4b4'
    red:     '#f99f92'
    green:   '#e3f7a1'
    yellow:  '#f2e9bf'
    blue:    '#b3d2ff'
    magenta: '#e5bdff'
    cyan:    '#c2fefa'
    white:   '#ffffff'

cursor:
  # Cursor style
  #
  # Values for 'style':
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Block

key_bindings:
  - { key: F11, action: ToggleFullscreen }
