set -g mouse on

bind-key / copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -selection clipboard'

# Avoid ESC delay in Vim
set -sg escape-time 0

# Truecolor support for attached terminal clients
set -as terminal-features ',xterm-256color:RGB'
set -as terminal-features ',xterm-ghostty:RGB'

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sessionist'

# Window title / activity
set -g automatic-rename on
set -g set-titles on
setw -g monitor-activity on

# Prefix
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

# Splits
bind-key v split-window -h
bind-key s split-window -v

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Pane resizing
bind-key J resize-pane -D 5
bind-key K resize-pane -U 5
bind-key H resize-pane -L 5
bind-key L resize-pane -R 5

# Status bar
set -g status-position bottom
set -g status-interval 1
set -g status-left ''
set -g status-right '#[fg=#afffff] #H #[fg=#767676]%d/%m %T '

set -g status-style 'bg=#121212,fg=#444444'

set -g window-status-style 'bg=#121212,fg=#808080'
set -g window-status-format ' #I:#W#F '

set -g window-status-current-style 'bg=#ffffd7,fg=#000000'
set -g window-status-current-format ' #I:#W#F '

set -g window-status-activity-style 'bg=#767676,fg=#080808'
set -g window-status-bell-style 'bg=#af005f,fg=#1c1c1c'
set -g window-status-last-style 'bg=#121212,fg=#808080'

# TPM must stay last
run '~/.tmux/plugins/tpm/tpm'
